# Generated by Django 4.1 on 2022-08-09 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proc_deals', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deals',
            new_name='Deal',
        ),
    ]
